name: Markdown lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install pymarkdown
        run: pip install pymarkdownlnt
      - name: Run pymarkdown
        run: pymarkdown --config .pymarkdown.json scan .
